packageExtensions:
  "@chakra-ui/accordion@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@*":
    peerDependencies:
      framer-motion: "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  "@pmmmwh/react-refresh-webpack-plugin@*":
    dependencies:
      webpack-hot-middleware: "*"
  "@storybook/core@*":
    peerDependencies:
      webpack: "*"
  "@storybook/preset-create-react-app@*":
    peerDependencies:
      react-refresh: "*"
      typescript: "*"
      webpack: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
