packageExtensions:
  "@chakra-ui/accordion@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@emotion/react": "*"
  "@chakra-ui/switch@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": "*"
  "@pmmmwh/react-refresh-webpack-plugin@*":
    dependencies:
      react-refresh: "*"
      webpack-hot-middleware: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"
  "@mikro-orm/knex@*":
    dependencies:
      "@mikro-orm/migrations": "*"
  "@eflexsystems/adminjs-koa@*":
    dependencies:
      "koa2-formidable": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
