packageExtensions:
  "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/clickable@*":
    peerDependencies:
      "@chakra-ui/react-utils": "*"
  "@chakra-ui/portal@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/radio@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/react-utils@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/system@*":
    dependencies:
      "@chakra-ui/react-utils": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/toast@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/tooltip@*":
    dependencies:
      "@chakra-ui/react-utils": "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": "*"
  "@pmmmwh/react-refresh-webpack-plugin@*":
    dependencies:
      webpack-hot-middleware: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
