packageExtensions:
  "@chakra-ui/accordion@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@*":
    peerDependencies:
      framer-motion: "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": "*"
  "@pmmmwh/react-refresh-webpack-plugin@*":
    dependencies:
      webpack-hot-middleware: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
