packageExtensions:
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/theme@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": "*"
  "@mikro-orm/core@*":
    dependencies:
      "@mikro-orm/cli": "*"
      "@mikro-orm/reflection": "*"
  "@mikro-orm/knex@*":
    dependencies:
      "@mikro-orm/migrations": "*"
  # "@pmmmwh/react-refresh-webpack-plugin@*":
  #   dependencies:
  #     react-refresh: "*"
  #     webpack-hot-middleware: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"
  # "eslint@*":
  #   dependencies:
  #     "eslint-config-react-app": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpIgnorePatterns:
  - ./packages/client-mobile/*

yarnPath: .yarn/releases/yarn-3.2.3.cjs
