packageExtensions:
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/theme@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@chakra-ui/theme-tools@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@mikro-orm/core@*":
    dependencies:
      "@mikro-orm/cli": "*"
      "@mikro-orm/reflection": "*"
  "@mikro-orm/knex@*":
    dependencies:
      "@mikro-orm/migrations": "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@storybook/mdx2-csf": "*"
  "@storybook/builder-vite@*":
    dependencies:
      "@storybook/client-api": "*"
  "@storybook/mdx2-csf@*":
    dependencies:
      "@babel/types": "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"
  eslint@*:
    dependencies:
      typescript-eslint/recommended: "*"
  local-pkg@*:
    dependencies:
      "@vitest/coverage-c8": "*"
      jsdom: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpIgnorePatterns:
  - ./packages/client-mobile/**

yarnPath: .yarn/releases/yarn-3.6.3.cjs
