packageExtensions:
  "@chakra-ui/accordion@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/anatomy@*":
    peerDependencies:
      "@chakra-ui/system": "*"
  "@chakra-ui/button@*":
    peerDependencies:
      "@chakra-ui/react-utils": "*"
  "@chakra-ui/react@*":
    peerDependencies:
      "@chakra-ui/react-utils": "*"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": 11.4.1
      "@emotion/styled": "*"
  "@chakra-ui/switch@*":
    peerDependencies:
      framer-motion: "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": 11.4.1
  "@pmmmwh/react-refresh-webpack-plugin@*":
    dependencies:
      react-refresh: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": 11.4.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
