compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/theme-tools@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@chakra-ui/theme@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@mikro-orm/core@*":
    dependencies:
      "@mikro-orm/cli": "*"
      "@mikro-orm/reflection": "*"
  "@mikro-orm/knex@*":
    dependencies:
      "@mikro-orm/migrations": "*"
      pg: "*"
      sqlite3: "*"
  "@mikro-orm/postgresql@*":
    dependencies:
      "postgres-array": "*"
  "@sentry-internal/replay-canvas@*":
    dependencies:
      "@sentry/utils": "*"
  "@storybook/mdx2-csf@*":
    dependencies:
      "@babel/types": "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"
  eslint@*:
    dependencies:
      typescript-eslint/recommended: "*"
  local-pkg@*:
    dependencies:
      "@vitest/coverage-c8": "*"
      jsdom: "*"

pnpIgnorePatterns:
  - ./packages/client-mobile/**

yarnPath: .yarn/releases/yarn-4.1.0.cjs
