packageExtensions:
  "@chakra-ui/accordion@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@emotion/react": "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/styled": "*"
      "@emotion/react": "*"
  "@chakra-ui/switch@*":
    peerDependencies:
      framer-motion: "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": "*"
  "@pmmmwh/react-refresh-webpack-plugin@*":
    dependencies:
      react-refresh: "*"
      webpack-hot-middleware: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
