# Extends docker-compose.yml, adding analytics support using Plausible analytics
# Usage: `docker compose -f docker-compose.yml -f docker-compose.analytics.yml up`
# Docs: https://plausible.io/docs/self-hosting-configuration
version: "3.8"

x-service-defaults: &service-defaults
  restart: unless-stopped
  networks:
    - sass-starter-net

networks:
  sass-starter-net:

volumes:
  clickhouse_data: {}
  geoip_data: {}

services:
  client-web:
    environment:
      REACT_APP_PLAUSIBLE_HOST: https://plausible.localtest.me

  clickhouse:
    <<: *service-defaults
    # image: yandex/clickhouse-server:21.3
    # Use this image if running on ARM64 (i.e. Mac M1) until a multi-arch image
    # is available from yandex: https://github.com/ClickHouse/ClickHouse/issues/22222
    image: altinity/clickhouse-server:21.6.1.6734-testing-arm
    environment:
      CLICKHOUSE_DB: plausible
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./services/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./services/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  geoip:
    image: maxmindinc/geoipupdate
    environment:
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country
      GEOIPUPDATE_FREQUENCY: 168 # update every 7 days
      GEOIPUPDATE_ACCOUNT_ID:
      GEOIPUPDATE_LICENSE_KEY:
    volumes:
      - geoip_data:/usr/share/GeoIP

  plausible:
    <<: *service-defaults
    image: plausible/analytics:v1.3
    command: sh -c "sleep 10 && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - postgres
      - clickhouse
      - mail
      - geoip
    environment:
      ADMIN_USER_EMAIL: macadam@example.com
      ADMIN_USER_NAME: macadam
      ADMIN_USER_PWD: macadam!
      DISABLE_AUTH: "true"
      BASE_URL: https://plausible.localtest.me
      SECRET_KEY_BASE: USbJSimhObRflMa+UC8iku9Iqhpr1RtPeLaEl8uuJpI44X+zoha1L9Jeo/7dgKUMZtMTGnDTsgYfYxcQ40ZSAA==
      DATABASE_URL: postgresql://plausible:plausible!@postgres:5432/plausible
      CLICKHOUSE_DATABASE_URL: http://clickhouse:8123/plausible
      SMTP_HOST_ADDR: mail
      SMTP_HOST_PORT: 1025
      GEOLITE2_COUNTRY_DB: /geoip/GeoLite2-Country.mmdb
    volumes:
      - geoip_data:/geoip:ro
