# Extends docker-compose.yml, adding GlitchTip for crash reporting
# Usage: `docker compose -f docker-compose.yml -f docker-compose.glitchtip.yml up`

version: "3.8"

x-service-defaults: &service-defaults
  restart: unless-stopped
  networks:
    - sass-starter-net

networks:
  sass-starter-net:

services:
  glitchtip-migrate:
    <<: *service-defaults
    image: glitchtip/glitchtip
    depends_on:
      - postgres
      - redis
    command: bash -c "./manage.py migrate && ./manage.py seed_macadam"
    restart: on-failure
    volumes:
      - ./services/glitchtip/commands/seed_macadam.py:/code/glitchtip/management/commands/seed_macadam.py
    environment:
      DATABASE_URL: postgresql://glitchtip:glitchtip!@postgres:5432/glitchtip
      SECRET_KEY: change_me

  glitchtip-web:
    <<: *service-defaults
    # NOTE: On AMD64 you will be spamemd with messages like:
    # "*** uWSGI listen queue of socket ":8000" (fd: 3) full !!! (26472960/64) ***"
    # I can't figure out how to fix this. Rebuilding the docker image fails on
    # AMD64 when installing symbolic (see: https://github.com/getsentry/symbolic/issues/76).
    # There seems to be no other adverse effects, though, so I've given up on this for now.
    image: glitchtip/glitchtip
    depends_on:
      - glitchtip-migrate
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: 512M
        reservations:
          cpus: "0.0001"
          memory: 256M
    environment:
      DATABASE_URL: postgresql://glitchtip:glitchtip!@postgres:5432/glitchtip
      SECRET_KEY: change_me
      EMAIL_URL: smtp://mail:1025/?skip_ssl_verify=true
      DEFAULT_FROM_EMAIL: glitchtip@example.com
      GLITCHTIP_DOMAIN: https://glitchtip.localtest.me
      PORT: 8000
      ENABLE_OPEN_USER_REGISTRATION: "true"

  glitchtip-worker:
    <<: *service-defaults
    image: glitchtip/glitchtip
    command: celery -A glitchtip worker -B -l INFO
    depends_on:
      - glitchtip-migrate
    environment:
      DATABASE_URL: postgresql://glitchtip:glitchtip!@postgres:5432/glitchtip
      SECRET_KEY: change_me
      EMAIL_URL: smtp://mail:1025/?skip_ssl_verify=true
      GLITCHTIP_DOMAIN: https://glitchtip.localtest.me
