# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "macadam"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "alert.rules"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kratos"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["kratos:4434"]

  - job_name: "kratos-courier"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["kratos-courier:4434"]

  - job_name: "api-server"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-server:9464"]

  - job_name: "caddy"
    static_configs:
      - targets: ["caddy:2019"]

  - job_name: "postgres"
    scrape_interval: 10s
    static_configs:
      - targets: ["postgres-exporter:9187"]
