version: v0.6.3-alpha.1

sqa-opt-out: true

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/kratos/public
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:4455/
  whitelisted_return_urls:
    - https://localhost/
    - https://localtest.me

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: TODO
            client_secret: TODO
            mapper_url: file:///etc/config/kratos/oidc.github.jsonnet
            scope:
              - user:email
          - id: google
            provider: google
            client_id: TODO
            client_secret: TODO
            scope:
              - offline
            mapper_url: file:///etc/config/kratos/oidc.google.jsonnet
          - id: slack
            provider: slack
            client_id: TODO
            client_secret: TODO
            mapper_url: file:///etc/config/kratos/oidc.slack.jsonnet
            scope:
              - identity.basic
              - identity.email
    lookup_secret:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: Macadam
    webauthn:
      config:
        rp:
          id: localhost
          display_name: Macadam
          # icon: https://www.ory.sh/an-icon.png
          # origin: https://www.ory.sh/login
      enabled: true
    profile:
      enabled: true
    link:
      enabled: true
      config:
        # Defines how long a recovery link is valid for (default 1h)
        lifespan: 3h # TODO: check OWASP guidance

  flows:
    error:
      ui_url: http://localhost:4455/error

    settings:
      ui_url: http://localhost:4455/settings
      privileged_session_max_age: 15m # TODO: check OWASP recommentation? 5m maybe?

    recovery:
      enabled: true
      lifespan: 30m
      ui_url: http://localhost:4455/recovery

    verification:
      enabled: true
      lifespan: 1h
      ui_url: http://localhost:4455/verify

    logout:
      after:
        default_browser_return_url: http://localhost:4455/auth/login

    login:
      lifespan: 1h
      ui_url: http://localhost:4455/auth/login

    registration:
      lifespan: 2h
      ui_url: http://localhost:4455/auth/registration
      after:
        password:
          hooks:
            # This hooks logs users in immediately after registration. This
            # means an account enumeration attack will be possible.
            # comment this out to disable, but it will require the user to
            # manually login after registering
            # https://www.ory.sh/kratos/docs/concepts/security#account-enumeration-attacks
            # See here for implementation status: https://github.com/ory/kratos/issues/133
            - hook: session
        oidc:
          hooks:
            - hook: session

log:
  level: info
  format: json
  leak_sensitive_values: false

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  # Be sure to update the `traitsSchema` on the client to reflect any changes to
  # the identity schema(s): `packages/client-web/src/features/identity/schemas/identity.ts`
  default_schema_url: file:///etc/config/kratos/email-password.schema.json

session:
  cookie:
    name: macadam_session
  lifespan: 720h # 30 days

expose-metrics-port: 4434

courier:
  smtp:
    connection_uri: smtp://mailhog:1025/?disable_starttls=true
    # from_name: Bob # TODO
    # from_address: aaa@a.aa # TODO
  template_override_path: /conf/courier-templates
