version: v0.6.3-alpha.1

sqa-opt-out: true

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/kratos/public
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:4455/
  allowed_return_urls:
    - https://localhost/

  methods:
    password:
      enabled: true
    oidc:
      # Disabled until we can figure out how to get it to work in react native.
      # See:
      # - https://github.com/ory/kratos/discussions/2434
      # - https://github.com/ory/kratos/pull/2346
      # - https://github.com/ory/kratos/issues/707
      # Possible using one/some of these?
      # - https://dev.to/safaiyeh/react-native-authentication-with-webview-1nh
      # - https://github.com/FormidableLabs/react-native-app-auth
      # - https://github.com/react-native-webview/react-native-webview
      enabled: false
      config:
        providers:
          - id: twitch
            provider: generic
            client_id: REPLACE_ME
            client_secret: REPLACE_ME
            issuer_url: https://id.twitch.tv/oauth2
            mapper_url: file:///etc/config/kratos/oidc.twitch.jsonnet
            scope:
              - openid
              - user:read:email # required for email and email_verified claims in the near future
            requested_claims: # explicitly request email and email_verified claims because twitch doesn't add them by default
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                picture: null
                preferred_username: null
          - id: discord
            provider: discord
            client_id: "REPLACE_ME"
            client_secret: REPLACE_ME
            mapper_url: file:///etc/config/kratos/oidc.discord.jsonnet
            scope:
              - identify
              - email
          - id: microsoft
            provider: microsoft
            client_id: "REPLACE_ME"
            client_secret: "REPLACE_ME"
            microsoft_tenant: consumers
            mapper_url: file:///etc/config/kratos/oidc.microsoft.jsonnet
            scope:
              - profile
              - email
          - id: facebook
            provider: facebook
            client_id: "REPLACE_ME"
            client_secret: REPLACE_ME
            mapper_url: file:///etc/config/kratos/oidc.facebook.jsonnet
            scope:
              - email
          - id: github
            provider: github
            client_id: REPLACE_ME
            client_secret: REPLACE_ME
            mapper_url: file:///etc/config/kratos/oidc.github.jsonnet
            scope:
              - user:email
          - id: google
            provider: google
            client_id: REPLACE_ME
            client_secret: REPLACE_ME
            scope:
              - email
              - profile
            mapper_url: file:///etc/config/kratos/oidc.google.jsonnet
    lookup_secret:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: Macadam
    webauthn:
      config:
        rp:
          id: localhost
          display_name: Macadam
          # icon: https://www.ory.sh/an-icon.png
          # origin: https://www.ory.sh/login
      enabled: true
    profile:
      enabled: true
    link:
      enabled: true
      config:
        # Defines how long a recovery link is valid for (default 1h)
        lifespan: 3h # TODO: check OWASP guidance

  flows:
    error:
      ui_url: http://localhost:4455/error

    settings:
      ui_url: http://localhost:4455/settings
      privileged_session_max_age: 15m # TODO: check OWASP recommentation? 5m maybe?

    recovery:
      enabled: true
      lifespan: 30m
      ui_url: http://localhost:4455/recovery

    verification:
      enabled: true
      lifespan: 1h
      ui_url: http://localhost:4455/verify

    logout:
      after:
        default_browser_return_url: http://localhost:4455/auth/login

    login:
      lifespan: 1h
      ui_url: http://localhost:4455/auth/login

    registration:
      lifespan: 2h
      ui_url: http://localhost:4455/auth/registration
      after:
        password:
          hooks:
            # This hooks logs users in immediately after registration. This
            # means an account enumeration attack will be possible.
            # comment this out to disable, but it will require the user to
            # manually login after registering
            # https://www.ory.sh/kratos/docs/concepts/security#account-enumeration-attacks
            # See here for implementation status: https://github.com/ory/kratos/issues/133
            - hook: session
        oidc:
          hooks:
            - hook: session

log:
  level: info
  format: json
  leak_sensitive_values: false

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: user_v1
  schemas:
    - id: user_v1
      # Be sure to update the `traitsSchema` on the client to reflect any changes to
      # the identity schema(s): `packages/client-web/src/features/identity/schemas/identity.ts`
      url: file:///etc/config/kratos/user_v1.schema.json

session:
  cookie:
    name: macadam_session
  lifespan: 720h # 30 days

expose-metrics-port: 4434

courier:
  smtp:
    connection_uri: smtp://mailhog:1025/?disable_starttls=true
    # from_name: Bob # TODO
    # from_address: aaa@a.aa # TODO
  template_override_path: /conf/courier-templates
